<?php

namespace AppBundle\Repository;

/**
 * Boisson3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Boisson3Repository extends \Doctrine\ORM\EntityRepository
{
}
