<?php

namespace AppBundle\Repository;

/**
 * Dessert3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dessert3Repository extends \Doctrine\ORM\EntityRepository
{
}
