<?php

namespace AppBundle\Repository;

/**
 * Menu3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Menu3Repository extends \Doctrine\ORM\EntityRepository
{
}
