<?php

namespace AppBundle\Repository;

/**
 * Menu_containerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Menu_containerRepository extends \Doctrine\ORM\EntityRepository
{
}
