<?php

namespace AppBundle\Repository;

/**
 * Menu_listsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Menu_listsRepository extends \Doctrine\ORM\EntityRepository
{
}
