AppBundle\Entity\Boisson:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nom
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        pm:
            - NotBlank: ~
            - Type: string
        gm:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Utilisateurs:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: pseudo
    properties:
        pseudo:
            - NotBlank: ~
            - Type: string
        nom:
            - NotBlank: ~
            - Type: string
        prenom:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Type: string
        role:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Dessert:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nom
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        prix:
            - NotBlank: ~
            - Type: string
        ingredient:
            - NotBlank: ~
            - Type: string